---
- name: Set default iptables policies to ACCEPT during configuration
  ansible.builtin.iptables:
    policy: ACCEPT
    chain: "{{ item }}"
  loop: [ 'INPUT', 'OUTPUT', 'FORWARD' ]
 
- name: Flush all existing iptables rules to prevent connection blocks
  ansible.builtin.iptables:
    flush: yes

- name: Update apt cache
  apt: # Use the apt module to update the package cache
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - wget
      - vim
      - nano
      - git
      - unzip
      - jq
      - net-tools
      - tcpdump
      - traceroute
      - htop
      - rsync
      - tar
      - python3
      - python-pip3
      - fail2ban
      - iptables-persistent
      - ntp
    state: present # Ensure the packages are installed

- name: Download and Run Docker installation script
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present

- name: Export usr/sbin and /sbin in .bashrc path
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regexp: ':/usr/sbin:/sbin'
    line: 'export PATH=$PATH:/usr/sbin:/sbin'
    state: present

- name: Configure user .bashrc history to include date & timestamp
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    regexp: '^export HISTTIMEFORMAT='
    line: 'export HISTTIMEFORMAT="%F %T "'
    state: present

- name: Enable & Start NTP service
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes