---
- name: Change the default SSH port in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port\s+\d+'
    line: "Port 22444"


- name: Restart the sshd service to apply the new port config
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Update ansible_port in memory for the rest of the playbook
  ansible.builtin.set_fact:
    ansible_port: 22444

- name: Enable Fail2ban service
  ansible.builtin.service: #enable fail2ban service
    name: fail2ban
    state: started
    enabled: yes

- name: Config fail2ban jail.local
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true 
      port = 22444 
      filter = sshd 
      logpath = /var/log/auth.log 
      maxretry = 5
      bantime = 3600
      findtime = 600

- name: Restart fail2ban to apply the new config
  ansible.builtin.service:
    name: fail2ban
    state: restarted 
  
- name: Allow loopback (lo) traffic (INPUT)
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

#allow loopback (for network interface card (NIC))
- name: Allow loopback (lo) traffic (OUTPUT)
  ansible.builtin.iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT

#allow all localhost traffic
- name: Allow any incoming traffic destined for localhost subnet
  ansible.builtin.iptables:
    chain: INPUT
    destination: 127.0.0.0/8
    jump: ACCEPT

#for existing connections (conntrack)
- name: Allow established & related connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ['ESTABLISHED', 'RELATED']
    jump: ACCEPT

- name: Allow established & related connections (OUTPUT)
  ansible.builtin.iptables:
    chain: OUTPUT
    ctstate: ['ESTABLISHED', 'RELATED']
    jump: ACCEPT

- name: Allow all outbound traffic from server (Temporary for setup)
  ansible.builtin.iptables:
    chain: OUTPUT
    jump: ACCEPT

# allow ssh connection on the new custom port
- name: Allow SSH connection on the custom port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    jump: ACCEPT

#allow ping (icmp)
- name: Allow ICMP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: echo-request
    jump: ACCEPT

# Allow port 1194 for openVPN  and tun (virtual network interface card)
- name: Allow OpenVPN traffic on port 1194
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: "1194"
    jump: ACCEPT

- name: Allow incoming traffic on tun interface
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: tun+
    jump: ACCEPT

- name: Forward traffic from tun interface
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: tun+
    jump: ACCEPT

# nat (masquerade) for OpenVPN
- name: Configure NAT masquerade for OpenVPN subnet
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: 10.8.0.0/24
    jump: MASQUERADE

- name: Set Default iptables policies
  ansible.builtin.iptables:
    policy: "{{ item.policy }}"
    chain: "{{ item.chain }}"
  loop:
    - { chain: 'INPUT', policy: 'DROP'}
    - { chain: 'OUTPUT', policy: 'DROP'}
    - { chain: 'FORWARD', policy: 'ACCEPT'}

# save iptables rules
- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
