---
- name: Create OpenVPN configuration directory
  ansible.builtin.file:
    path: /etc/openvpn_data
    state: directory
    mode: '0700'

- name: Run OpenVPN Container
  community.docker.docker_container:
    name: openvpn
    image: kylemanna/openvpn:latest
    state: started 
    restart_policy: always
    ports:
      - "1194:1194/udp"
    volumes:
      - /etc/openvpn_data:/etc/openvpn
    capabilities:
      - NET_ADMIN 

- name: Wait for OpenVPN container to be running and stable
  community.docker.docker_container_info:
    name: openvpn
  register: container_status
  until: >
    container_status.container.State.Running == true and
    container_status.container.State.Restarting == false
  retries: 15
  delay: 5

- name: Initialize OpenVPN configuration inside the container
  ansible.builtin.command: docker exec openvpn ovpn_genconfig -u udp://{{ ansible_host }}:1194
  args:
    creates: /etc/openvpn_data/openvpn.conf
  register: genconfig_result
  retries: 5
  delay: 5
  until: genconfig_result is not failed

- name: Initialize PKI CA
  ansible.builtin.command: docker exec -e EASYRSA_BATCH=1 openvpn ovpn_initpki nopass
  args:
    creates: /etc/openvpn_data/pki/ca.crt

- name: Generate OpenVPN client credential without password
  ansible.builtin.command: docker exec openvpn ovpn_getclient client
  register: client_cfg
  args:
    creates: /etc/openvpn_data/client.ovpn

- name: Check if client config file already exists on host
  ansible.builtin.stat:
    path: /etc/openvpn_data/client.ovpn
  register: vpn_cert_file

- name: Save client config file on host
  ansible.builtin.copy:
    content: "{{ client_cfg.stdout }}"
    dest: /etc/openvpn_data/client.ovpn
    mode: '0600'
  when: client_cfg.changed or not vpn_cert_file.stat.exists

- name: Fetch OpenVPN client certificate content
  ansible.builtin.slurp:
    src: /etc/openvpn_data/client.ovpn
  register: vpn_cert

- name: Print VPN certificate for jenkins
  ansible.builtin.debug:
    msg: "START_CERTIFICATE_OUTPUT\n{{ vpn_cert['content'] | b64decode }}\nEND_CERTIFICATE_OUTPUT"